INSERT INTO clientes (preferencia, sueldo_minimo, sueldo_maximo, edad_minima, edad_maxima, tipo_tarjeta) VALUES('Shoping', 6999, 15000, 17, 33, 'B*smart');
INSERT INTO clientes (preferencia, sueldo_minimo, sueldo_maximo, edad_minima, edad_maxima, tipo_tarjeta) VALUES('Shoping', 14999, 100000 , 17, 24, 'B*smart');
INSERT INTO clientes (preferencia, sueldo_minimo, sueldo_maximo, edad_minima, edad_maxima, tipo_tarjeta) VALUES('My style', 6999, 15000, 17, 76, 'B*smart');
INSERT INTO clientes (preferencia, sueldo_minimo, sueldo_maximo, edad_minima, edad_maxima, tipo_tarjeta) VALUES('My style', 14999, 35000, 17, 33, 'B*smart');
INSERT INTO clientes (preferencia, sueldo_minimo, sueldo_maximo, edad_minima, edad_maxima, tipo_tarjeta) VALUES('My style', 34999, 100000 , 17, 76, 'B*smart');
INSERT INTO clientes (preferencia, sueldo_minimo, sueldo_maximo, edad_minima, edad_maxima, tipo_tarjeta) VALUES('Shoping', 6999, 35000, 17, 33, 'Afinity Card');
INSERT INTO clientes (preferencia, sueldo_minimo, sueldo_maximo, edad_minima, edad_maxima, tipo_tarjeta) VALUES('Shoping', 34999, 100000 , 17, 24, 'Afinity Card');
INSERT INTO clientes (preferencia, sueldo_minimo, sueldo_maximo, edad_minima, edad_maxima, tipo_tarjeta) VALUES('My style', 6999, 35000, 17, 33, 'Afinity Card');
INSERT INTO clientes (preferencia, sueldo_minimo, sueldo_maximo, edad_minima, edad_maxima, tipo_tarjeta) VALUES('Shoping', 6999, 15000, 23, 76, 'Clasica');
INSERT INTO clientes (preferencia, sueldo_minimo, sueldo_maximo, edad_minima, edad_maxima, tipo_tarjeta) VALUES('hoping', 6999, 50000, 23, 76, 'Office Depot, \nCostco, \nBest Buy Banamex, \nThe Home Depot');
INSERT INTO clientes (preferencia, sueldo_minimo, sueldo_maximo, edad_minima, edad_maxima, tipo_tarjeta) VALUES('My business', 6999, 100000 , 17, 76, 'Office Depot, \nCostco, \nBest Buy Banamex, \nThe Home Depot');
INSERT INTO clientes (preferencia, sueldo_minimo, sueldo_maximo, edad_minima, edad_maxima, tipo_tarjeta) VALUES('Shoping', 14999, 35000, 23, 76, 'Oro');
INSERT INTO clientes (preferencia, sueldo_minimo, sueldo_maximo, edad_minima, edad_maxima, tipo_tarjeta) VALUES('My style', 14999, 30000, 23, 76, 'Oro');
INSERT INTO clientes (preferencia, sueldo_minimo, sueldo_maximo, edad_minima, edad_maxima, tipo_tarjeta) VALUES('Shoping', 34999, 100000 , 23, 76, 'Platinum');
INSERT INTO clientes (preferencia, sueldo_minimo, sueldo_maximo, edad_minima, edad_maxima, tipo_tarjeta) VALUES('Travels', 29999, 100000 , 23, 76, 'Platinum');
INSERT INTO clientes (preferencia, sueldo_minimo, sueldo_maximo, edad_minima, edad_maxima, tipo_tarjeta) VALUES('My style', 29999, 100000 , 23, 76, 'Platinum');
INSERT INTO clientes (preferencia, sueldo_minimo, sueldo_maximo, edad_minima, edad_maxima, tipo_tarjeta) VALUES('Travels', 11999, 50000, 17, 76, 'Citi / AAdvantage');
INSERT INTO clientes (preferencia, sueldo_minimo, sueldo_maximo, edad_minima, edad_maxima, tipo_tarjeta) VALUES('Travels', 49999, 100000 , 17, 23, 'Citi / AAdvantage');
INSERT INTO clientes (preferencia, sueldo_minimo, sueldo_maximo, edad_minima, edad_maxima, tipo_tarjeta) VALUES('Help',11999, 100000 , 17, 76, 'Banamex Teleton, \nAPAC');
INSERT INTO clientes (preferencia, sueldo_minimo, sueldo_maximo, edad_minima, edad_maxima, tipo_tarjeta) VALUES('Sports', 6999, 35000, 17, 76, 'Marti Clasica Citibanamex, \nAmerica Deporteismo, \nPumas Deporteismo, \nToluca Deporteismo, \nLa verde Deporteismo');
INSERT INTO clientes (preferencia, sueldo_minimo, sueldo_maximo, edad_minima, edad_maxima, tipo_tarjeta) VALUES('Sports', 34999, 100000 , 17, 76, 'Marti Premium Citibanamex');